version: '2'
services:
   notifier:
      image: shoppinpal/notifier
      ports:
        - "3000:3000"
      depends_on:
        - redis
   redis:
      image: redis:2.8
      ports:
        - "6379:6379"
